version: '3.8'

services:
  vscode:
    build: .
    container_name: vscodeweb
    environment:
      - SENHA_UBT: ${SENHA_UBT:-senha_para_alterar}
    volumes:
      - container_data/vscode:/home
      - /container_data:/home/shared
    entrypoint: "/entrypoint.sh"
    # entrypoint: ["/bin/sh", "/entrypoint.sh"]
    ports:
      - 80  # Mapeia a porta 80 para uma porta aleatória que sera capturada pelo coolify
    restart: unless-stopped
